openapi: 3.0.0
info:
  title: Gestion de Pólizas
  description: API para la gestión de pólizas y partes de seguros de automóviles.
  version: 1.0.0
servers:
  - url: https://localhost:8081/policies
  - url: https://localhost:8081/parts

tags:
  - name: policies
    description: Operaciones sobre pólizas
  - name: parts
    description: Operaciones sobre partes de siniestros
  - name: policyTypes
    description: Operaciones sobre tipos de pólizas
  - name: states
    description: Operaciones sobre estados

paths:
  /policyTypes:
    get:
      tags:
        - policyTypes
      summary: Obtener todos los tipos de pólizas
      operationId: getAllPolicyTypes
      responses:
        '200':
          description: Lista de tipos de pólizas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PolicyType'

  /policyTypes/{id}:
    get:
      tags:
        - policyTypes
      summary: Obtener un tipo de póliza por ID
      operationId: getPolicyTypeById
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Tipo de póliza encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PolicyType'
        '404':
          description: Tipo de póliza no encontrado
  /states:
    get:
      tags:
        - states
      summary: Obtener todos los estados
      operationId: getAllStates
      responses:
        '200':
          description: Lista de estados
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/State'
  /states/{id}:
    get:
      tags:
        - states
      summary: Obtener un estado por ID
      operationId: getStateById
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Estado encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/State'
        '404':
          description: Estado no encontrado
  /policies:
    post:
      tags:
        - policies
      summary: Creación de una póliza
      description: Crea una nueva póliza en el sistema
      operationId: savePolicy
      requestBody:
        required: true
        description: Póliza a crear
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Policy'
      responses:
        '201':
          description: Póliza creada correctamente
    get:
      tags:
        - policies
      summary: Obtener todas las pólizas
      operationId: getAllPolicies
      responses:
        '200':
          description: Lista de pólizas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Policy'

  /policies/{id}:
    get:
      tags:
        - policies
      summary: Obtener detalles de una póliza
      operationId: getPolicyById
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Detalles de la póliza
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Policy'
        '404':
          description: Póliza no encontrada
    put:
      tags:
        - policies
      summary: Actualizar una póliza existente
      operationId: updatePolicy
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        description: Datos actualizados de la póliza
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Policy'
      responses:
        '200':
          description: Póliza actualizada correctamente
        '404':
          description: Póliza no encontrada
    delete:
      tags:
        - policies
      summary: Eliminar una póliza
      operationId: deletePolicyById
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Póliza eliminada correctamente

  /policies/user/{dni}:
    get:
      tags:
        - policies
      summary: Obtener póliza por DNI de usuario
      operationId: getPolicyByDni
      parameters:
        - in: path
          name: dni
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Póliza del usuario
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Policy'

  /policies/vehicle/{matricula}:
    get:
      tags:
        - policies
      summary: Obtener póliza por matrícula del vehículo
      operationId: getPolicyByMatricula
      parameters:
        - in: path
          name: matricula
          required: true
          schema:
            type: string
      responses:
        '200':
          description: póliza del vehículo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Policy'

  /parts:
    post:
      tags:
        - parts
      summary: Crear un parte de siniestro
      operationId: savePart
      requestBody:
        required: true
        description: Parte a crear
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Part'
      responses:
        '201':
          description: Parte creado correctamente
    get:
      tags:
        - parts
      summary: Obtener todos los partes
      operationId: getAllParts
      responses:
        '200':
          description: Lista de partes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Part'

components:
  schemas:
    PolicyType:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
      required:
        - name
        - description

    State:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
      required:
        - name
        - description

    Policy:
      type: object
      properties:
        id:
          type: integer
        userId:
          type: integer
        vehicleId:
          type: integer
        beneficiaryId:
          type: integer
        iban:
          type: string
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
        policyTypeId:
          type: integer
        active:
          type: boolean
        premiumAmount:
          type: number
          format: double
      required:
        - userId
        - vehicleId
        - beneficiaryId
        - iban
        - startDate
        - endDate
        - policyTypeId
        - premiumAmount

    Part:
      type: object
      properties:
        id:
          type: integer
        policyId:
          type: integer
        thirdPartyId:
          type: integer
        thirdPartyVehicleId:
          type: integer
        placeEvent:
          type: string
        description:
          type: string
        accidentDate:
          type: string
          format: date-time
        dateOfRegistration:
          type: string
          format: date-time
        dateOfLastUpdate:
          type: string
          format: date-time
        stateId:
          type: integer
      required:
        - policyId
        - description
        - accidentDate
        - dateOfRegistration
        - stateId